FROM node:18-alpine AS builder

# Build arguments from .env file
ARG REACT_APP_BACKEND_URL
ARG REACT_APP_NAME
ARG REACT_APP_SHORT_NAME
ARG REACT_APP_COMPANY_NAME
ARG REACT_APP_COMPANY_URL
ARG REACT_APP_DESCRIPTION
ARG REACT_APP_TAGLINE
ARG REACT_APP_CONTACT_EMAIL
ARG REACT_APP_COPYRIGHT_HOLDER

# Set environment variables for React build
ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL
ENV REACT_APP_NAME=$REACT_APP_NAME
ENV REACT_APP_SHORT_NAME=$REACT_APP_SHORT_NAME
ENV REACT_APP_COMPANY_NAME=$REACT_APP_COMPANY_NAME
ENV REACT_APP_COMPANY_URL=$REACT_APP_COMPANY_URL
ENV REACT_APP_DESCRIPTION=$REACT_APP_DESCRIPTION
ENV REACT_APP_TAGLINE=$REACT_APP_TAGLINE
ENV REACT_APP_CONTACT_EMAIL=$REACT_APP_CONTACT_EMAIL
ENV REACT_APP_COPYRIGHT_HOLDER=$REACT_APP_COPYRIGHT_HOLDER

WORKDIR /app

RUN apk add --no-cache python3 make g++

COPY frontend/package.json .
COPY frontend/package-lock.json .
RUN npm ci --omit=dev

COPY frontend/ .

RUN npm run build

# Stage 2: Serve the app with Nginx
FROM nginx:stable-alpine

# Copy the Nginx configuration
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

# Copy the built React app from the builder stage
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]