version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    environment:
      FLASK_ENV: production
      SECRET_KEY: ${SECRET_KEY}
      ADMIN_MAIL: ${ADMIN_MAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    expose:
      - "5000"
    depends_on:
      - redis
    networks:
      - main
    volumes:
      - db_data:/app/instance

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - main

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    networks:
      - main

volumes:
  db_data:

networks:
  main:
    driver: bridge