"""Add avatar field to User model

Revision ID: 293531c9dc9c
Revises: 8d0e3f45a95b
Create Date: 2025-12-16 22:16:48.608862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293531c9dc9c'
down_revision = '8d0e3f45a95b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
